blockExoticSubdeps: true

childConcurrency: 1

ignoredBuiltDependencies:
  - better-sqlite3
  - core-js-pure
  - dtrace-provider
  - protobufjs
  - re2

allowBuilds:
  better-sqlite3: false
  core-js-pure: false
  dtrace-provider: false
  lefthook: true
  protobufjs: false
  re2: false

strictDepBuilds: true
