#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm exec syncpack fix-mismatches || exit 1
pnpm exec syncpack set-semver-ranges || exit 1
pnpm exec syncpack format || exit 1

pnpm install
pnpm exec lint-staged || exit 1
pnpm exec renovate-config-validator --strict default.json
git add package.json pnpm-lock.yaml default.json
